version: '3'

services:

  traefik:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api
      - --certificatesresolvers.le.acme.email=mail@simlau.dk
      - --certificatesresolvers.le.acme.storage=./acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/simlau/traefik/acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.simlau.dk`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - traefik.http.middlewares.authtraefik.basicauth.users=
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    container_name: traefik
    restart: unless-stopped
  ddb-proxy:
    image: ghcr.io/mrprimate/ddb-proxy:latest
    hostname: ddb-proxy
    container_name: ddb-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ddb-proxy.rule=Host(`ddb-proxy.simlau.dk`)"
      - "traefik.http.routers.ddb-proxy.entrypoints=websecure"
      - "traefik.http.routers.ddb-proxy.tls=true"
      - "traefik.http.routers.ddb-proxy.tls.certresolver=le"
    ports:
      - 3000:3000
    networks:
      - proxy
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry
    container_name: foundry
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundry.rule=Host(`foundry.simlau.dk`)"
      - "traefik.http.routers.foundry.entrypoints=websecure"
      - "traefik.http.routers.foundry.tls=true"
      - "traefik.http.routers.foundry.tls.certresolver=le"
    ports:
      - 30000:30000
    environment:
      - FOUNDRY_USERNAME=
      - FOUNDRY_PASSWORD=
      - FOUNDRY_ADMIN_KEY=
    volumes:
      - /home/simlau/foundry:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
